apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "devops-info-service.fullname" . }}
  labels:
    {{- include "devops-info-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "devops-info-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "devops-info-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
  strategy:
    blueGreen:
      activeService: { { include "devops-info-service.fullname" . } }
      previewService: { { include "devops-info-service.fullname" . } }-preview
      autoPromotionEnabled: false