replicaCount: 1

image:
  repository: devops-info-service
  tag: "lab12"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 5000

containerPort: 5000

secret:
  enabled: true
  nameOverride: ""
  data:
    username: "change-me"
    password: "change-me"

vault:
  enabled: false

  role: "devops-info"
  secretPath: "secret/data/devops-info-service/config"
  fileName: "config"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

livenessProbe:
  enabled: true
  path: /health
  port: 5000
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3

readinessProbe:
  enabled: true
  path: /health
  port: 5000
  initialDelaySeconds: 5
  periodSeconds: 3
  timeoutSeconds: 2
  failureThreshold: 3

nameOverride: ""
fullnameOverride: ""

hooks:
  enabled: true
  image: "busybox:1.36"
  preInstall:
    sleepSeconds: 5
  postInstall:
    sleepSeconds: 5

environment: dev
logLevel: info

persistence:
  size: 100Mi
  storageClass: ""