{{- if .Values.hooks.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "devops-info-service.fullname" . }}-post-install"
  labels:
    {{- include "devops-info-service.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "devops-info-service.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: post-install
          image: {{ .Values.hooks.image | quote }}
          command:
            - sh
            - -c
            - >
              echo "[post-install] starting";
              sleep {{ .Values.hooks.postInstall.sleepSeconds }};
              echo "[post-install] done";
{{- end }}